spring.application.name=unit2_bakers-blog
spring.datasource.url=jdbc:mysql://localhost:3306/bakersblog_sql
spring.datasource.username=root
spring.datasource.password=Ramdun#21
spring.jpa.hibernate.ddl-auto=update